# This file was generated by GoReleaser. DO NOT EDIT.
class Bump < Formula
  desc "bump returns next semantic version tag."
  homepage "https://github.com/haya14busa/bump"
  version "1.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/haya14busa/bump/releases/download/v1.0.1/bump_1.0.1_Darwin_x86_64.tar.gz"
    sha256 "3dc84dadd722e52b44a46721661347fb3e646fa23d03dec3432c0d20adcda1ff"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/haya14busa/bump/releases/download/v1.0.1/bump_1.0.1_Linux_x86_64.tar.gz"
      sha256 "e572b21a90954238f41a20caa33ac9b9eb980d5711888ac684ac36c41bc3cac8"
    end
  end

  def install
    bin.install "bump"
  end

  test do
    system "#{bin}/bump -h"
  end
end
