# This file was generated by GoReleaser. DO NOT EDIT.
class Bump < Formula
  desc "bump returns next semantic version tag."
  homepage "https://github.com/haya14busa/bump"
  version "1.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/haya14busa/bump/releases/download/v1.1.0/bump_1.1.0_Darwin_x86_64.tar.gz"
    sha256 "4c04f70264e5678557344962a502a6cf571bddb67a64b90ae9a903ea7fe904cf"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/haya14busa/bump/releases/download/v1.1.0/bump_1.1.0_Linux_x86_64.tar.gz"
      sha256 "fa4ebd5ebe8706435ee34ba5d1837e2960ad50fa184e12a1a950c5e9fc16a942"
    end
  end

  def install
    bin.install "bump"
  end

  test do
    system "#{bin}/bump -h"
  end
end
