# This file was generated by GoReleaser. DO NOT EDIT.
class Ghglob < Formula
  desc "ghglob is glob, or more like pattern matcher based on GitHub Actions's Filter pattern spec."
  homepage "https://github.com/haya14busa/ghglob"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/haya14busa/ghglob/releases/download/v1.0.0/ghglob_1.0.0_Darwin_x86_64.tar.gz"
    sha256 "51fd9f9e6ff450deb4896f3e3a8e4b498ef79dcb9099b7faf0b85b2588f88508"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/haya14busa/ghglob/releases/download/v1.0.0/ghglob_1.0.0_Linux_x86_64.tar.gz"
      sha256 "1817b832a5ae8a6e2e766c43998b80dec520189439ad151d5ee26eaa2a390ca5"
    end
  end

  def install
    bin.install "ghglob"
  end

  test do
    system "#{bin}/ghglob -version"
  end
end
