# This file was generated by GoReleaser. DO NOT EDIT.
class Ghglob < Formula
  desc "ghglob is glob, or more like pattern matcher based on GitHub Actions's Filter pattern spec."
  homepage "https://github.com/haya14busa/ghglob"
  version "2.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/haya14busa/ghglob/releases/download/v2.0.1/ghglob_2.0.1_Darwin_x86_64.tar.gz"
    sha256 "0244e69573a4b51605df2023f790df58946264ebbadfc922c33579df38b08ff4"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/haya14busa/ghglob/releases/download/v2.0.1/ghglob_2.0.1_Linux_x86_64.tar.gz"
      sha256 "3ff744f07b23bbc371f353b45399815383e796aa1bf518dab37ee9059a5ddb25"
    end
  end

  def install
    bin.install "ghglob"
  end

  test do
    system "#{bin}/ghglob -version"
  end
end
