# This file was generated by GoReleaser. DO NOT EDIT.
class Tmpl < Formula
  desc "Generate textual output using Go text/template from given data in STDIN"
  homepage "https://github.com/haya14busa/tmpl"
  version "1.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/haya14busa/tmpl/releases/download/v1.0.1/tmpl_1.0.1_darwin_amd64.tar.gz"
    sha256 "47c403f6c3fa648a577a0998336651f01b4a2083f5319dbfaa5def8e98a15685"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/haya14busa/tmpl/releases/download/v1.0.1/tmpl_1.0.1_linux_amd64.tar.gz"
      sha256 "3062a1c4797fa8f4a12eef356bab93a629d1bc49c3219d9678d585bce237cb17"
    end
  end

  def install
    bin.install "tmpl"
  end

  test do
    system "#{bin}/tmpl -version"
  end
end
