# This file was generated by GoReleaser. DO NOT EDIT.
class Tmpl < Formula
  desc "Generate textual output using Go text/template from given data in STDIN"
  homepage "https://github.com/haya14busa/tmpl"
  version "1.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/haya14busa/tmpl/releases/download/v1.2.0/tmpl_1.2.0_darwin_amd64.tar.gz"
    sha256 "0da280a1881a345b95127d219df165bbc0b34b3da7f76e61a3005ce6ab1055f3"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/haya14busa/tmpl/releases/download/v1.2.0/tmpl_1.2.0_linux_amd64.tar.gz"
      sha256 "dc48dd6407c7fd93d291c3a8ab535a6803fdab495b9a19bd3c78bb7519eb74be"
    end
  end

  def install
    bin.install "tmpl"
  end

  test do
    system "#{bin}/tmpl -version"
  end
end
