# This file was generated by GoReleaser. DO NOT EDIT.
class Tmpl < Formula
  desc "Generate textual output using Go text/template from given data in STDIN"
  homepage "https://github.com/haya14busa/tmpl"
  version "1.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/haya14busa/tmpl/releases/download/v1.1.0/tmpl_1.1.0_darwin_amd64.tar.gz"
    sha256 "fc640ff589ac90b36274cff7fe5e7cee53f1b24d0254c5afe5b1671d9a30e68d"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/haya14busa/tmpl/releases/download/v1.1.0/tmpl_1.1.0_linux_amd64.tar.gz"
      sha256 "aed697237bf8748c0e604276b043adcb7a424f5ded4e4ffd09b5f422a2ccb2cc"
    end
  end

  def install
    bin.install "tmpl"
  end

  test do
    system "#{bin}/tmpl -version"
  end
end
